In [2]:
import numpy as np
import math

## 1
Given, there are 5 numbers in the data set: (8, 12, 16, 24, 4). What is the standard deviation? And, what will be the sum of deviations of individual data points from their mean?

In [3]:
# manually
mean = (8 + 12 + 16 + 24 + 4) / 5
variance = ((mean - 8) ** 2 + (mean - 12) ** 2 + (mean - 16) ** 2 + (mean - 24) ** 2 + (mean - 4) ** 2) / 5
st_dev = math.sqrt(variance)
print(f"Manually calculated standard deviation is {st_dev}")

np_arr = np.array([8, 12, 16, 24, 4])
print(f"NumPy standard deviation is {np_arr.std()}")
print(f"Shape: {np_arr.shape}")
print(f"Dimentions: {np_arr.ndim}")
print(f"Size: {np_arr.size}")


Manually calculated standard deviation is 6.881860213634101
NumPy standard deviation is 6.881860213634101
Shape: (5,)
Dimentions: 1
Size: 5


In [4]:
arr = np.random.randint(0, 10, (10, 10))

In [5]:
print(arr)
print(arr[:, [2,8]])

[[7 5 0 9 6 8 2 2 9 4]
 [2 6 4 3 1 8 5 0 8 3]
 [1 4 3 6 2 4 2 9 4 3]
 [1 9 8 3 3 0 0 2 7 6]
 [1 4 2 3 4 3 3 8 3 9]
 [6 6 9 3 5 9 4 5 9 6]
 [2 8 2 1 9 0 9 7 3 7]
 [4 6 0 9 7 1 8 8 1 4]
 [6 0 7 9 2 3 5 4 2 8]
 [5 6 5 3 8 0 1 2 4 9]]
[[0 9]
 [4 8]
 [3 4]
 [8 7]
 [2 3]
 [9 9]
 [2 3]
 [0 1]
 [7 2]
 [5 4]]


## 2
If some outliers are introduced to the dataset, what will happen to the Standard Deviation? Will it increase, decrease or remain the same?
A: it will increase

## 3 (no numpy)
Suppose the below positively skewed distribution has a median of 30, which of the following statement is true?

A) Mean is greater than 30 - T
B) Mean is less than 30 - F
C) Mode is greater than 30 - F
D) Mode is less than 30 - T
E) Both A and D - T
F) Both B and C - F
![](https://caberlin-lms-v3.herokuapp.com/assets/data/Module-1/Project-1/stat-2.jpg)

## 4
Which value can be the possible value for the median of the below distribution?
![](https://caberlin-lms-v3.herokuapp.com/assets/data/Module-1/Project-1/stat-3.jpg)

Assume the data are distributed as follows:
[10, 10, 10, 10, 11, 11, 12, 13, 14 ]
[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19]
[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24]
[26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29]
[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34]
[35, 35, 35, 37, 37, 37, 37, 39, 39, 39]
[40, 40, 43, 43, 44, 44]
[46, 46, 46, 47, 49]
[52, 53, 54]

In [6]:
data_dist = [
    [10, 10, 10, 10, 11, 11, 12, 13, 14 ],
    [15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19],
    [20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24],
    [26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29],
    [30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34],
    [35, 35, 35, 37, 37, 37, 37, 39, 39, 39],
    [40, 40, 43, 43, 44, 44],
    [46, 46, 46, 47, 49],
    [52, 53, 54],
]
a = np.array([])
for el in data_dist:
    a = np.concatenate((a, np.array(el)))
print("Mean value is", np.median(a))


Mean value is 27.0


## 5,6,7
![](https://caberlin-lms-v3.herokuapp.com/assets/data/Module-1/Project-1/stat-4.jpg)
What is the shape of the distribution? (no Numpy)
A: positively skewed

What would you consider to be the most appropriate measure of the center for this data?
A: median

If Y axis represents the number of individuals and X axis – salary of the individual in thousands. How many individuals have salary less than 10 thousands? (no Numpy)
A: 24 + 12 = 36

We have a set of positive numbers. If a single value of the set is altered what must change?

A) Mean
B) Median
C) Mode
D) All of these
A: D, but sometimes Mode is not altered

Hint: try to create a Numpy array and calculate mean median and mode, then alter it and see what changes

In [7]:
# from scipy import stats as st

a = np.array([71, 37,  2, 40, 15,  4, 86, 85, 30,  1, 96,  3, 64, 26,  5, 60, 63,
       85, 47, 13])
print("Mean: ", a.mean())
print("Median: ", np.median(a))
# print("Mode: ", st.mode(a))

Mean:  41.65
Median:  38.5


## 9
The chart shows hourly consultancy rate of 10 people.

Calculate the standard deviation of the salaries of the 10 employees.

![](https://caberlin-lms-v3.herokuapp.com/assets/data/Module-1/Project-1/stat-5.jpg)

In [8]:
a = np.array([25, 25, 25, 40, 40, 35, 50, 50, 50, 50])
print("STD is", a.std())

STD is 10.44030650891055


## 10 (no Numpy)
Which of the following random variables is discrete?

A) the length of time a battery lasts
B) the number of pens purchased by a student in a year
C) the percentage of cows in a cattle firm that have been vaccinated
D) the distance between a pair of towns
- B

## 11 (no numpy)
Which of the below normal distributions will have the greatest spread?

A) mu=5, sigma =1.5
B) mu=10, sigma =1.0
C) mu=5, sigma =1.65 <------
D) mu=8, sigma =1.2
E) mu=10, sigma =1.6