In [121]:
#### 1. Import the numpy package under the name `np`
import numpy as np

In [122]:
#### 2. Print the numpy version and the configuration
print(np.version)
np.show_config()

<module 'numpy.version' from '/home/user/anaconda3/envs/env310/lib/python3.10/site-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_',

In [123]:
#### 3. Create a null vector of size 10
null_vestor_10 = np.zeros(10)
print(null_vestor_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [124]:
#### 4. How to find the memory size of any array
print(null_vestor_10.itemsize, "bytes")

8 bytes


In [125]:
#### 5. How to get the documentation of the numpy add function from the command line?
# help np.add

In [126]:
#### 6. Create a null vector of size 10 but the fifth value which is 1
a6 = np.zeros(10)
a6[4] = 1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [127]:
#### 7. Create a vector with values ranging from 10 to 49
a7 = np.arange(10, 50)
print(a7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [128]:
#### 8. Reverse a vector (first element becomes last)
a7_flipped = np.flip(a7)
print(a7_flipped)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [129]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8
a9 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [130]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
a10 = np.array([1,2,0,0,4,0])
print(np.where(a10 == 0))

(array([2, 3, 5]),)


In [131]:
#### 11. Create a 3x3 identity matrix
a11 = np.eye(3)
print(a11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [132]:
#### 12. Create a 3x3x3 array with random values
a12 = np.random.random((3,3))
print(a12)

[[0.6652298  0.73856238 0.56127914]
 [0.65461261 0.68283943 0.00322766]
 [0.31337725 0.23374392 0.04285761]]
