https://raw.githubusercontent.com/rougier/numpy-100/master/100_Numpy_exercises.md

In [56]:
#### 1. Import the numpy package under the name `np`
import numpy as np

In [57]:
#### 2. Print the numpy version and the configuration
print(np.version)
np.show_config()

<module 'numpy.version' from '/home/user/anaconda3/envs/env310/lib/python3.10/site-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_',

In [58]:
#### 3. Create a null vector of size 10
null_vestor_10 = np.zeros(10)
print(null_vestor_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [59]:
#### 4. How to find the memory size of any array
print(null_vestor_10.nbytes, "bytes")

80 bytes


In [60]:
#### 5. How to get the documentation of the numpy add function from the command line?
# help np.add

In [61]:
#### 6. Create a null vector of size 10 but the fifth value which is 1
a6 = np.zeros(10)
a6[4] = 1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [62]:
#### 7. Create a vector with values ranging from 10 to 49
a7 = np.arange(10, 50)
print(a7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [63]:
#### 8. Reverse a vector (first element becomes last)
a7_flipped = np.flip(a7)
print(a7_flipped)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [64]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8
a9 = np.arange(9).reshape(3, 3)
print(a9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
a10 = np.array([1,2,0,0,4,0])
print(np.where(a10 == 0))

(array([2, 3, 5]),)


In [66]:
#### 11. Create a 3x3 identity matrix
a11 = np.eye(3)
print(a11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
#### 12. Create a 3x3x3 array with random values
np.random.seed(0)
a12 = np.random.randint(100, size=(3,3))
print(a12)

[[44 47 64]
 [67 67  9]
 [83 21 36]]


In [68]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values
a13 = np.random.randint(100, size=(10,10))
print(a13)
print('max', np.max(a13))
print('min', np.min(a13))

[[87 70 88 88 12 58 65 39 87 46]
 [88 81 37 25 77 72  9 20 80 69]
 [79 47 64 82 99 88 49 29 19 19]
 [14 39 32 65  9 57 32 31 74 23]
 [35 75 55 28 34  0  0 36 53  5]
 [38 17 79  4 42 58 31  1 65 41]
 [57 35 11 46 82 91  0 14 99 53]
 [12 42 84 75 68  6 68 47  3 76]
 [52 78 15 20 99 58 23 79 13 85]
 [48 49 69 41 35 64 95 69 94  0]]
max 99
min 0


In [69]:
#### 14. Create a random vector of size 30 and find the mean value
a14 = np.random.randint(100, size=30)
print(a14)
print("mean", a14.mean())

[50 36 34 48 93  3 98 42 77 21 73  0 10 43 58 23 59  2 98 62 35 94 67 82
 46 99 20 81 50 27]
mean 51.03333333333333


In [70]:
#### 15. Create a 2d array with 1 on the border and 0 inside
a15 = np.zeros((10,10))
a15[0] = 1
a15[-1] = 1
a15[:,0] = 1
a15[:,-1] = 1
print(a15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [71]:
#### 16. How to add a border (filled with 0's) around an existing array?
hborder = np.zeros(10)
vborder = np.zeros(12).reshape(12, 1)
a15 = np.vstack([hborder, a15, hborder])
a15 = np.hstack([vborder, a15, vborder])
print(a15)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [72]:
#### 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [73]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
size = 5
a18 = np.zeros((size,size))

for i in range(1, size):
    a18[i, i-1] = i

print(a18)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [74]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern
size = 8
a18 = np.zeros((size,size))
a18[::2,::2] = 1
a18[1::2,1::2] = 1
print(a18)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [75]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import math

def get_coords(sx, sy, sz, el_num):
    el_cnt_in_z = sx * sy
    z = el_num // el_cnt_in_z
    y = (el_num % el_cnt_in_z) // sx
    x = el_num - y * sx * sz
    return (x, y, z)

sx = 6
sy = 7
sz = 8
el_num = 100
a20 = np.random.randint(100, size=(sx,sy,sz))

print(a20)
print(get_coords(sx, sy, sz, el_num))



[[[14 41 58 65 36 10 86 43]
  [11  2 51 80 32 54  0 38]
  [19 46 42 56 60 77 30 24]
  [ 2  3 94 98 13 40 72 19]
  [95 72 26 66 52 67 61 14]
  [96  4 67 11 86 77 75 56]
  [16 24 29 21 25 80 60 61]]

 [[83 33 32 70 85 31 13 71]
  [56 24 79 41 18 40 54 79]
  [11 38 93  1 95 44 88 24]
  [67 82  3 76 35 86 61 69]
  [87 43 32 11 84 10 54 37]
  [28  2 27 83 89 23 53 51]
  [46 20 53 29 67 35 39  9]]

 [[73 41 23  3 46 90 50  3]
  [31  9 10 27 45 71 39 61]
  [85 97 44 34 34 88 33  5]
  [36  0 75 34 69 53 80 62]
  [ 8 61  1 81 35 91 40 36]
  [48 25 67 35 30 29 33 18]
  [17 93 84  2 69 12 44 66]]

 [[91 85 39 39 75 22 30 17]
  [70 71 18 92 43 83 49 41]
  [93 46 21 73 89 96 91 73]
  [28 81 58  0 86 63 16 36]
  [94 24 63 67 51  8 56 91]
  [93 87 32 19 72 71 87 13]
  [58 81 55 64 75 92 36 25]]

 [[32 42 14 86 28 20 82 68]
  [22 99 83  7 72 61 13  5]
  [ 0  8 79 79 53 11  4 39]
  [92 45 26 74 52 49 91 51]
  [99 18 34 51 30 53 58 43]
  [55 18 45 87 65 70 53 48]
  [94 59 80 26 35 58 49 73]]

 [[44 13 7

In [76]:
#### 21. Create a checkerboard 8x8 matrix using the tile function
a21 = np.array([[1,0], [0,1]])
print(np.tile(a21, (8,8)))

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [77]:
#### 22. Normalize a 5x5 random matrix
a22 = np.random.randint(100, size=(5,5))
print(np.linalg.norm(a22))

295.8665239597072


In [78]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
rgb_dt = np.dtype('>i4')
print(rgb_dt.itemsize)

4


In [79]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a24_1 = np.random.randint(100, size=(5,3))
a24_2 = np.random.randint(100, size=(3,2))
print(a24_1)
print(a24_2)
print(np.matmul(a24_1, a24_2))

[[39 24 58]
 [36 99 69]
 [ 6  3 98]
 [40 60 33]
 [28 68 26]]
[[96 51]
 [73 53]
 [69 33]]
[[ 9498  5175]
 [15444  9360]
 [ 7557  3699]
 [10497  6309]
 [ 9446  5890]]


In [80]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place
a25 = np.random.randint(100, size=50)

def negt(x):
    if x >=3 and x <= 8:
        return -x
    else:
        return x

np_neg = np.vectorize(negt)

print(a25)
print(np_neg(a25))

[ 7 94 72 84  7 67 85 91 67 84 71 83 95  0  5 91 30 73 83  7 21 92  8 43
 46  0 51 38 89 74 98 87 96 83 26 78 32 70 97 44 59 57 50 45  4 57 93 91
 17 35]
[-7 94 72 84 -7 67 85 91 67 84 71 83 95  0 -5 91 30 73 83 -7 21 92 -8 43
 46  0 51 38 89 74 98 87 96 83 26 78 32 70 97 44 59 57 50 45 -4 57 93 91
 17 35]


In [81]:
#### 26. What is the output of the following script?
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [82]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z  -< illegal


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [83]:
#### 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_7179/1284412314.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_7179/1284412314.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_7179/1284412314.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [84]:
#### 29. How to round away from zero a float array ?
a29 = np.random.random(10)
a29 *= 100
print(a29)
print(np.ceil(a29))

[53.92235974 32.56847664 14.70138949 15.98700671 12.94123374 57.89223875
  9.22601704 91.05447224  8.29717477 80.03784621]
[54. 33. 15. 16. 13. 58. 10. 92.  9. 81.]


In [85]:
#### 30. How to find common values between two arrays?
a30 = np.random.randint(10, size=20)
b30 = np.random.randint(10, size=20)
print(a30)
print(b30)
print(np.intersect1d(a30, b30))

[7 6 6 2 3 6 0 8 0 7 6 5 9 6 5 2 7 1 9 2]
[2 5 6 4 2 2 1 0 9 0 2 8 3 0 8 8 1 0 5 8]
[0 1 2 3 5 6 8 9]


In [86]:
#### 31. How to ignore all numpy warnings (not recommended)?
# numpy.seterr(all='ignore')

In [87]:
#### 32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_7179/3472255086.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [88]:
#### 33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
print(today - np.timedelta64(1, 'D'))
print(today)
print(today + np.timedelta64(1, 'D'))

2023-02-13
2023-02-14
2023-02-15


In [89]:
#### 34. How to get all the dates corresponding to the month of July 2016?
a34 = np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), np.timedelta64(1, "D"))
print(a34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [90]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
a35 = np.random.randint(10, size=10)
b35 = np.random.randint(10, size=10)
print(a35)
print(b35)
print((a35+b35)*(-a35/2))

[2 3 5 3 8 6 4 6 3 6]
[2 6 5 5 9 4 6 5 1 3]
[ -4.  -13.5 -25.  -12.  -68.  -30.  -20.  -33.   -6.  -27. ]


In [91]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
a21 = np.arange(0,5)
print(np.tile(a21, (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [92]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def gen_ints(n):
    for i in range(n):
        yield i
print(np.fromiter(gen_ints(10), int))



[0 1 2 3 4 5 6 7 8 9]


In [93]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
print(np.random.random(10))

[0.1154843  0.61848026 0.97425621 0.990345   0.4090541  0.16295443
 0.63876176 0.49030535 0.98940978 0.06530421]


In [94]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
a40 = np.random.random(10)
print(np.sort(a40))

[0.24141862 0.24606318 0.28705152 0.2883985  0.42408899 0.51730852
 0.55468781 0.66250457 0.66585912 0.78323444]


In [95]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
import timeit
a41 = range(100)
n41 = np.array(a41)

def py_sum():
    return sum(a41)

def np_sum_on_py_list():
    return np.sum(a41)

def np_sum_on_np_arr():
    return np.sum(a41)

print("python sum", timeit.timeit(py_sum, number=10000))
print("np sum on python list", timeit.timeit(np_sum_on_py_list, number=10000))
print("np sum on python list", timeit.timeit(np_sum_on_np_arr, number=10000))


python sum 0.009625856999264215
np sum on python list 0.09516812200126878
np sum on python list 0.08602564399916446


In [96]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
a42 = np.random.randint(10, size=5)
b42 = np.random.randint(10, size=5)
print(a42 == b42)
print(np.array_equal(a42, b42))

[False False False False False]
False


In [97]:
#### 43. Make an array immutable (read-only) (★★☆)
a43 = np.random.randint(10, size=5)
a43.setflags(write=False)
a43[0] = 1

ValueError: assignment destination is read-only

In [118]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
a44 = np.random.randint(100, size=(10,2))
b44 = np.zeros((10,2), dtype="float")

print('cartesian coordinates\n', a44)

x = a44[:,0].reshape(10,).copy()
y = a44[:,1].reshape(10,).copy()
b44[:,0] = np.sqrt(x**2 + y**2)
b44[:,1] = np.arctan(y / x) * 180 / math.pi

print('\npolar coordinates\n', b44)

cartesian coordinates
 [[ 7 29]
 [78 11]
 [73 11]
 [16 60]
 [63 59]
 [ 1 18]
 [53 28]
 [64 85]
 [88 73]
 [ 8 82]]

polar coordinates
 [[ 29.83286778  76.42956561]
 [ 78.77182237   8.02723751]
 [ 73.8241153    8.56914188]
 [ 62.09669879  75.06858282]
 [ 86.31338251  43.12212255]
 [ 18.02775638  86.82016988]
 [ 59.94163828  27.84757826]
 [106.40018797  53.02240365]
 [114.33722054  39.67724929]
 [ 82.3893197   84.4278022 ]]


In [123]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
a45 = np.random.randint(10, size=10)
m = np.max(a45)
i = np.where(a45 == m)

print('before replacing', a45)

a45[i] = 0

print('after replacing', a45)

before replacing [9 4 9 0 6 5 3 0 0 1]
after replacing [0 4 0 0 6 5 3 0 0 1]


In [125]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
a46 = np.array(
    [[0,0], [0,1], [1,0], [1,1]],
    dtype=[('x', 'i4'), ('y', 'i4')]
)
print(a46)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[(0, 0) (0, 0)]
 [(0, 0) (1, 1)]
 [(1, 1) (0, 0)]
 [(1, 1) (1, 1)]]


In [129]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
a47 = np.random.randint(1, 10, size=10)
b47 = np.random.randint(1, 10, size=10)
print(1.0 / (a47.reshape((-1,1)) - b47))

[[-0.2        -1.         -0.14285714 -0.2        -0.2        -0.25
  -1.         -0.25        1.         -0.5       ]
 [ 1.          0.2        -1.          1.          1.          0.5
   0.2         0.5         0.14285714  0.25      ]
 [-0.16666667 -0.5        -0.125      -0.16666667 -0.16666667 -0.2
  -0.5        -0.2                inf -0.33333333]
 [-0.16666667 -0.5        -0.125      -0.16666667 -0.16666667 -0.2
  -0.5        -0.2                inf -0.33333333]
 [-0.25               inf -0.16666667 -0.25       -0.25       -0.33333333
          inf -0.33333333  0.5        -1.        ]
 [-0.2        -1.         -0.14285714 -0.2        -0.2        -0.25
  -1.         -0.25        1.         -0.5       ]
 [-0.5         0.5        -0.25       -0.5        -0.5        -1.
   0.5        -1.          0.25        1.        ]
 [        inf  0.25       -0.5                inf         inf  1.
   0.25        1.          0.16666667  0.33333333]
 [-0.16666667 -0.5        -0.125      -0.16666667

/tmp/ipykernel_7179/1354421915.py:4: RuntimeWarning: divide by zero encountered in divide
  print(1.0 / (a47.reshape((-1,1)) - b47))


In [133]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
print("int: min=", np.iinfo('int').min, "max=", np.iinfo('int').max)
print("float: min=", np.finfo('float').min, "max=", np.finfo('float').max)

int: min= -9223372036854775808 max= 9223372036854775807
float: min= -1.7976931348623157e+308 max= 1.7976931348623157e+308


In [127]:
#### 49. How to print all the values of an array? (★★☆)
# numpy.set_printoptions(threshold=sys.maxsize)

In [148]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
def find_closest_number(arr, num):
    # sort the array
    arr = np.sort(arr)

    # slice it into 2 parts, above our number and below it
    above_split = np.where(arr > num)
    below_split = np.where(arr < num)

    # find what those numbers are
    n_above = arr[above_split[0][0]]
    n_below = arr[below_split[0][-1]]

    # return the one that is closer
    if n_above - num > closest_to - n_below:
        return n_above
    else:
        return n_below

def find_closest_number2(arr, num):
    # sort the array
    arr = np.sort(arr)

    # find what those numbers are
    n_above = np.min(arr[arr > num])
    n_below = np.max(arr[arr < num])

    # return the one that is closer
    if n_above - closest_to > closest_to - n_below:
        return n_above
    else:
        return n_below

rand = np.random.RandomState(42)
a50 = rand.randint(100, size=20)
closest_to = 47

print(a50)
print(f'closest number to {closest_to} is {find_closest_number2(a50, closest_to)}')

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
closest number to 47 is 37


In [ ]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
a51 = np.array(
    [],
    dtype=[('x', 'i4'), ('y', 'i4'), ('rgb', '>i4')]
)
print(a46)

In [158]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
# The distance between two points using coordinates can be given as, d = √[(x2 x 2 − x1 x 1 )2 + (y2 y 2 − y1 y 1 )2], where (x1,y1 x 1 , y 1 ) and (x2,y2 x 2 , y 2 ) are the coordinates of the two points.
rand = np.random.RandomState(0)
a52 = rand.randint(100, size=(100,2))

distances = np.hstack([a52, np.zeros((100,1))])

for i, d in enumerate(distances):
    try:
        x1 = distances[i-1, 0]
        x2 = distances[i, 0]
        y1 = distances[i-1, 1]
        y2 = distances[i, 1]
        d[2] = np.sqrt(((x1 - x2) ** 2) + ((y1 - y2) ** 2))
    except KeyError:
        pass

print(distances)

[[ 44.          47.          46.04345773]
 [ 64.          67.          28.28427125]
 [ 67.           9.          58.07753438]
 [ 83.          21.          20.        ]
 [ 36.          87.          81.0246876 ]
 [ 70.          88.          34.0147027 ]
 [ 88.          12.          78.10249676]
 [ 58.          65.          60.90155991]
 [ 39.          87.          29.06888371]
 [ 46.          88.           7.07106781]
 [ 81.          37.          61.85466838]
 [ 25.          77.          68.81860214]
 [ 72.           9.          82.66196223]
 [ 20.          80.          88.00568163]
 [ 69.          79.          49.01020302]
 [ 47.          64.          26.62705391]
 [ 82.          99.          49.49747468]
 [ 88.          49.          50.35871325]
 [ 29.          19.          66.18912297]
 [ 19.          14.          11.18033989]
 [ 39.          32.          26.90724809]
 [ 65.           9.          34.71310992]
 [ 57.          32.          24.35159132]
 [ 31.          74.          49.39

In [ ]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [ ]:
#### 54. How to read the following file? (★★☆)
# ```
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11
# ```

