In [1271]:
#### 1. Import the numpy package under the name `np`
import numpy as np

In [1272]:
#### 2. Print the numpy version and the configuration
print(np.version)
np.show_config()

<module 'numpy.version' from '/home/user/anaconda3/envs/env310/lib/python3.10/site-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_',

In [1273]:
#### 3. Create a null vector of size 10
null_vestor_10 = np.zeros(10)
print(null_vestor_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [1274]:
#### 4. How to find the memory size of any array
print(null_vestor_10.nbytes, "bytes")

80 bytes


In [1275]:
#### 5. How to get the documentation of the numpy add function from the command line?
# help np.add

In [1276]:
#### 6. Create a null vector of size 10 but the fifth value which is 1
a6 = np.zeros(10)
a6[4] = 1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [1277]:
#### 7. Create a vector with values ranging from 10 to 49
a7 = np.arange(10, 50)
print(a7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [1278]:
#### 8. Reverse a vector (first element becomes last)
a7_flipped = np.flip(a7)
print(a7_flipped)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [1279]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8
a9 = np.arange(9).reshape(3, 3)
print(a9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1280]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
a10 = np.array([1,2,0,0,4,0])
print(np.where(a10 == 0))

(array([2, 3, 5]),)


In [1281]:
#### 11. Create a 3x3 identity matrix
a11 = np.eye(3)
print(a11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1282]:
#### 12. Create a 3x3x3 array with random values
np.random.seed(0)
a12 = np.random.randint(100, size=(3,3))
print(a12)

[[44 47 64]
 [67 67  9]
 [83 21 36]]


In [1283]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values
a13 = np.random.randint(100, size=(10,10))
print(a13)
print('max', np.max(a13))
print('min', np.min(a13))

[[87 70 88 88 12 58 65 39 87 46]
 [88 81 37 25 77 72  9 20 80 69]
 [79 47 64 82 99 88 49 29 19 19]
 [14 39 32 65  9 57 32 31 74 23]
 [35 75 55 28 34  0  0 36 53  5]
 [38 17 79  4 42 58 31  1 65 41]
 [57 35 11 46 82 91  0 14 99 53]
 [12 42 84 75 68  6 68 47  3 76]
 [52 78 15 20 99 58 23 79 13 85]
 [48 49 69 41 35 64 95 69 94  0]]
max 99
min 0


In [1284]:
#### 14. Create a random vector of size 30 and find the mean value
a14 = np.random.randint(100, size=30)
print(a14)
print("mean", a14.mean())

[50 36 34 48 93  3 98 42 77 21 73  0 10 43 58 23 59  2 98 62 35 94 67 82
 46 99 20 81 50 27]
mean 51.03333333333333


In [1285]:
#### 15. Create a 2d array with 1 on the border and 0 inside
a15 = np.zeros((10,10))
a15[0] = 1
a15[-1] = 1
a15[:,0] = 1
a15[:,-1] = 1
print(a15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [1286]:
#### 16. How to add a border (filled with 0's) around an existing array?
hborder = np.zeros(10)
vborder = np.zeros(12).reshape(12, 1)
a15 = np.vstack([hborder, a15, hborder])
a15 = np.hstack([vborder, a15, vborder])
print(a15)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [1287]:
#### 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [1288]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
size = 5
a18 = np.zeros((size,size))

for i in range(1, size):
    a18[i, i-1] = i

print(a18)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [1289]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern
size = 8
a18 = np.zeros((size,size))
a18[::2,::2] = 1
a18[1::2,1::2] = 1
print(a18)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [1290]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import math

def get_coords(sx, sy, sz, el_num):
    el_cnt_in_z = sx * sy
    z = el_num // el_cnt_in_z
    y = (el_num % el_cnt_in_z) // sx
    x = el_num - y * sx * sz
    return (x, y, z)

sx = 6
sy = 7
sz = 8
el_num = 100
a20 = np.random.randint(100, size=(sx,sy,sz))

print(a20)
print(get_coords(sx, sy, sz, el_num))



[[[14 41 58 65 36 10 86 43]
  [11  2 51 80 32 54  0 38]
  [19 46 42 56 60 77 30 24]
  [ 2  3 94 98 13 40 72 19]
  [95 72 26 66 52 67 61 14]
  [96  4 67 11 86 77 75 56]
  [16 24 29 21 25 80 60 61]]

 [[83 33 32 70 85 31 13 71]
  [56 24 79 41 18 40 54 79]
  [11 38 93  1 95 44 88 24]
  [67 82  3 76 35 86 61 69]
  [87 43 32 11 84 10 54 37]
  [28  2 27 83 89 23 53 51]
  [46 20 53 29 67 35 39  9]]

 [[73 41 23  3 46 90 50  3]
  [31  9 10 27 45 71 39 61]
  [85 97 44 34 34 88 33  5]
  [36  0 75 34 69 53 80 62]
  [ 8 61  1 81 35 91 40 36]
  [48 25 67 35 30 29 33 18]
  [17 93 84  2 69 12 44 66]]

 [[91 85 39 39 75 22 30 17]
  [70 71 18 92 43 83 49 41]
  [93 46 21 73 89 96 91 73]
  [28 81 58  0 86 63 16 36]
  [94 24 63 67 51  8 56 91]
  [93 87 32 19 72 71 87 13]
  [58 81 55 64 75 92 36 25]]

 [[32 42 14 86 28 20 82 68]
  [22 99 83  7 72 61 13  5]
  [ 0  8 79 79 53 11  4 39]
  [92 45 26 74 52 49 91 51]
  [99 18 34 51 30 53 58 43]
  [55 18 45 87 65 70 53 48]
  [94 59 80 26 35 58 49 73]]

 [[44 13 7

In [1291]:
#### 21. Create a checkerboard 8x8 matrix using the tile function
a21 = np.array([[1,0], [0,1]])
print(np.tile(a21, (8,8)))

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [1292]:
#### 22. Normalize a 5x5 random matrix
a22 = np.random.randint(100, size=(5,5))
print(np.linalg.norm(a22))

295.8665239597072


In [1293]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
rgb_dt = np.dtype('>i4')
print(rgb_dt.itemsize)

4


In [1294]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a24_1 = np.random.randint(100, size=(5,3))
a24_2 = np.random.randint(100, size=(3,2))
print(a24_1)
print(a24_2)
print(np.matmul(a24_1, a24_2))

[[39 24 58]
 [36 99 69]
 [ 6  3 98]
 [40 60 33]
 [28 68 26]]
[[96 51]
 [73 53]
 [69 33]]
[[ 9498  5175]
 [15444  9360]
 [ 7557  3699]
 [10497  6309]
 [ 9446  5890]]


In [1295]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place
a25 = np.random.randint(100, size=50)

def negt(x):
    if x >=3 and x <= 8:
        return -x
    else:
        return x

np_neg = np.vectorize(negt)

print(a25)
print(np_neg(a25))

[ 7 94 72 84  7 67 85 91 67 84 71 83 95  0  5 91 30 73 83  7 21 92  8 43
 46  0 51 38 89 74 98 87 96 83 26 78 32 70 97 44 59 57 50 45  4 57 93 91
 17 35]
[-7 94 72 84 -7 67 85 91 67 84 71 83 95  0 -5 91 30 73 83 -7 21 92 -8 43
 46  0 51 38 89 74 98 87 96 83 26 78 32 70 97 44 59 57 50 45 -4 57 93 91
 17 35]
