In [55]:
import pandas as pd
import numpy as np
pd.__version__

'1.5.2'

In [20]:
data = pd.Series([1,2,3,4,5])
print(data.index)
print(data.values)
print(data)

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [21]:
data = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
print(data.index)
print(data.values)
print(data)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [22]:
data['b']

2

In [74]:
movies = pd.read_csv('movies.csv')
# movies = movies[movies['Title'] != '']
# movies = movies[movies['Title'].notnull()]
movies = movies.dropna(thresh=9)

movies = movies.astype({
    'Release year': 'int',
    'Gross': 'int',
    'Budget': 'int'
})
print(movies.tail())
# print(movies.dtypes)

     MovieID                                  Title MPAA Rating     Budget  \
610      611         Godzilla: King of the Monsters       PG-13  200000000   
611      612                            Toy Story 4           G  200000000   
612      613  Fast & Furious Presents: Hobbs & Shaw       PG-13  200000000   
613      614                          The Lion King          PG  250000000   
614      615                      Avengers: Endgame       PG-13  356000000   

          Gross Release Date      Genre  Release year  Runtime  Rating  \
610   385900000   2019-05-13  Adventure          2019    132.0     NaN   
611  1062000000   2019-06-11  Animation          2019    100.0     NaN   
612   759400000   2019-07-13   Thriller          2019    136.0     NaN   
613  1632000000   2019-07-09      Drama          2019    118.0     NaN   
614  2796000000   2019-04-22     Action          2019    181.0     NaN   

     Rating Count Summary  
610           NaN     NaN  
611           NaN     NaN  
61

In [24]:
print("size", movies.index.size)
print("shape", movies.index.ndim)
print("dtype", movies.index.dtype)

size 616
shape 1
dtype int64


In [25]:
movies.keys()

Index(['MovieID', 'Title', 'MPAA Rating', 'Budget', 'Gross', 'Release Date',
       'Genre', 'Release year', 'Runtime', 'Rating', 'Rating Count',
       'Summary'],
      dtype='object')

In [37]:
movies_after_2000 = movies[movies['Release year'] >= 2000].head()
display(movies_after_2000.Title)

98                  Jurassic Park III
217    Crouching Tiger, Hidden Dragon
218                       Scary Movie
219                 Big Momma's House
220               Remember the Titans
Name: Title, dtype: object

In [51]:
import datetime
movies['Age'] = datetime.datetime.today().year - movies['Release year']
movies = movies.astype({'Age': 'int'})
display(movies.dtypes)
display(movies[['Title', 'Release year', 'Age']])

MovieID           int64
Title            object
MPAA Rating      object
Budget          float64
Gross           float64
Release Date     object
Genre            object
Release year      int64
Runtime         float64
Rating          float64
Rating Count    float64
Summary          object
Age               int64
dtype: object

Title  Release year  Age
0                       Look Who's Talking          1989   34
1                       Driving Miss Daisy          1989   34
2                           Turner & Hooch          1989   34
3               Born on the Fourth of July          1989   34
4                          Field of Dreams          1989   34
..                                     ...           ...  ...
611                            Toy Story 4          2019    4
612  Fast & Furious Presents: Hobbs & Shaw          2019    4
613                          The Lion King          2019    4
614                      Avengers: Endgame          2019    4
615                                    NaN          1899  124

[616 rows x 3 columns]

In [42]:
movies.values[14]

array([15, 'Ghostbusters II', 'PG', 37000000.0, 215394738.0, '1989-06-15',
       'Comedy', 1989, 108.0, 6.6, 171196.0,
       'The discovery of a massive river of ectoplasm and a resurgence of spectral activity allows the staff of Ghostbusters to revive the business.',
       34], dtype=object)

In [43]:
display(movies.iloc[:3, :2])

MovieID               Title
0        1  Look Who's Talking
1        2  Driving Miss Daisy
2        3      Turner & Hooch

In [45]:
display(movies.loc[18, 'Budget':'Release Date'])

Budget          55000000.0
Gross           63408614.0
Release Date    1989-12-22
Name: 18, dtype: object

In [52]:
movies.loc[movies['Age'] < 20, ['Title', 'Budget']]

Title       Budget
296                        Fahrenheit 9/11    6000000.0
297       DodgeBall: A True Underdog Story   20000000.0
298              The Passion of the Christ   30000000.0
299                            The Village   60000000.0
300                         50 First Dates   75000000.0
..                                     ...          ...
610         Godzilla: King of the Monsters  200000000.0
611                            Toy Story 4  200000000.0
612  Fast & Furious Presents: Hobbs & Shaw  200000000.0
613                          The Lion King  250000000.0
614                      Avengers: Endgame  356000000.0

[319 rows x 2 columns]

In [65]:
movies['Profit'] = movies['Gross'] - movies['Budget']
display(movies['Profit'])

0       288500000
1       138293296
2        58079915
3       147001698
4        69431625
          ...    
610     185900000
611     862000000
612     559400000
613    1382000000
614    2440000000
Name: Profit, Length: 615, dtype: int64

In [75]:
movies['actors'] = []

ValueError: Length of values (0) does not match length of index (615)